### ISSUE TITLE
`getName` on enum values returns their value, not their name (under some circumstances)

### ISSUE THREAD

**Issue by 9Morello** [YellowAfterlife/sfgml#12]
```
enum Test {
	foo;
	bar;
}

class Main {
	static function main() {
		var enValue:EnumValue = Test.foo;
		var name = enValue.getName();
		trace(name);
	}
}
```
This will output `0` on generated GML code, and `foo` on other Haxe targets .
If you set the type of `enValue` as `Test`, the generator does create a global array with the enum names for lookup.
This affects 2.3, 2.2 and legacy.

In addition, I can't compile the snippet above for >= 2.3 without adding `-D sfgml_version=2.3`, despite using `-D sfgml_modern`. Otherwise, I get the following error:
`sfgml/git/gml/internal/ArrayImpl.hx:59: characters 3-16 : Array resizing is only supported in 2.3+`
`-dce full` was enabled.

I've attached a sample project.
[enum_bug_test.zip](https://github.com/YellowAfterlife/sfgml/files/5397936/enum_bug_test.zip)

**Comment by 9Morello** [comment]
Further investigation shows that `getName` works more reliably on local variables than class fields or static variables.
```
enum Test {
	foo;
	bar;
}

class Main {

	static var staticValue:Test;

	static function main() {
		var localValue:Test = Test.foo;
		var name = localValue.getName();
		trace(name); //"foo" -> works! 

		staticValue = Test.bar;
		var name2 = staticValue.getName();
		trace(name2); //"1" -> doesn't work
	}
}
```

**Comment by YellowAfterlife** [comment]
sfgml collapses parameter-less enums into equivalent of enum abstracts, which replaces references to constructors with their IDs. This subsequently means that getName() only works if the type is known for the value as of invocation of helper functions.

The anomaly seen in the snippet is caused by a minor inconsistency in AST that Haxe compiler provides to sfgml - the code compiles as
```haxe
class Main {
	static var staticValue:Test;
	@:keep
	static function main():Void {
		var localValue:Test = Test.foo;
		var name:string = Type.enumConstructor(localValue);
		trace(name);
		Main.staticValue = Test.bar;
		var name2:string = Type.enumConstructor(cast Main.staticValue);
		trace(name2);
	}
}
```
That extra `cast` is what breaks it, as the resulting type is then not the enum itself, but EnumValue.

A bigger underlying question is whether collapsing is necessary with introduction of enum abstracts - both sfgml's behaviour and the linked post precede them by a few years.

**Comment by 9Morello** [comment]
Ohh, makes sense.
On enum abstracts, it'd be cool if we could add some metadata to force the generation of native enums. Using an int abstract is convenient writing code targeting GML.

Thanks for taking the time to look at this. <3

**Comment by YellowAfterlife** [comment]
You can force generation of native enums for 2.3 via @:doc for both enum abstracts and regular ones; for enum abstract you'll need to @:keep each member field for compiler to not eat them. On ≤2.2 this generates extension macros instead
