### ISSUE TITLE
Accessing nullable fields of a typedef doesn't work

### ISSUE THREAD

**Issue by 9Morello** [YellowAfterlife/sfgml#13]
```
typedef Foo = { ?bar1: Bool, ?bar2: Bool }

class Main {
	static function main() {
		var m:Foo = {};
		if (m.bar1 != null) trace('oops!');
		m.bar2 = true;
		if (m.bar2 != null) trace('OK!');
	}
}
```

This compiles to the following when targeting GMS2.3:
```
var _m = { }
if (_m.bar1 != undefined) trace("src/Main.hx:6:", "oops!");
_m.bar2 = true;
if (_m.bar2 != undefined) trace("src/Main.hx:10:", "OK!");
```
Which crashes because you can't read struct fields this way.

When targeting GMS2.2:
```
#define Main_main
// Main_main()
array_create(2)[1,0] = "Foo";
if (_m[0/* bar1 */] != undefined) trace("src/Main.hx:6:", "oops!");
_m[@1/* bar2 */] = true;
if (_m[1/* bar2 */] != undefined) trace("src/Main.hx:10:", "OK!");
```
Seems like the compiler is inlining something it shouldn't. `_m` is never declared. When you correct it by hand, the first `trace` is executed, but it shouldn't since we never defined `bar1`.

When targeting GMS1.4:
```
#define Main_main
// Main_main()
var _m = undefined;
_m[1,0] = "Foo";
_m[1] = 0;
if (_m[0/* bar1 */] != undefined) trace("src/Main.hx:6:", "oops!");
_m[@1/* bar2 */] = true;
if (_m[1/* bar2 */] != undefined) trace("src/Main.hx:10:", "OK!");
```
This does run out of the box, but `_m`'s fields should be both undefined instead of 0 on creation.

**Comment by YellowAfterlife** [comment]
- 2.3 behaviour is more of a fundamental difference between how by-spec Haxe and GML work.  
  `undefined` will now be assigned into "missing" fields, which will work for most cases.
- 2.2 behaviour was a side effect from replacing `var _m` with a two-statement block to declare m and then set name.  
  But also doing `_m[1, 0]` is illegal in 2.2.5 HTML5 so that's no longer done.
- Particularly old versions of 1.4 (pre-1773) will remain as-is as they do not support a two-argument version of `array_create`.

**Comment by 9Morello** [comment]
Thanks!
