### ISSUE TITLE
Breaking changes placed in Int64

### ISSUE THREAD

**Issue by XANOZOID** [YellowAfterlife/sfgml#8]
Some code was added to Int64 roughly 23 days ago that is now causing compile time errors. I've done a little bit of investigating but had to stop for now. The conflict seems to just be between modern and non-modern version of sfml since some new code added to the generator doesn't take into account the lack of dynamics in the prior versions. 

I've left messages on what has caused issues so far here -> https://github.com/YellowAfterlife/sfgml/commit/29f1cbd3f38cfad171e6309739fbc6f126b4e2a7

the int64 commit -> https://github.com/YellowAfterlife/sfgml/commit/29f1cbd3f38cfad171e6309739fbc6f126b4e2a7

There is probably more things that are broken, I just haven't had enough time to investigate further.  Or perhaps I'm not paying good attention and it is already stated somewhere where a divergence in sub 2.3 support started to break for a while. 

Do you think it would be possible to start tagging some commits or making branches for an easier workflow? Thanks!

**Comment by YellowAfterlife** [comment]
This is now fixed by https://github.com/YellowAfterlife/sfgml/commit/6af79bcf7a128ffeacf7b91f1b506fb3bd76b6b2

The issue had nothing to do with code generation - rather the new code hitting an edge case where it could not resolve type information (which is a requirement for pre-2.3).

I have been trying to get Haxe's standard library unit tests to compile but for now was not successful, only getting one or other nonsense error in return. For now there's only a small set of tests that I wrote to make sure that code is generated according to features used (as there's a subset of functions that should only be in output if a specific feature is used and had not been optimized away) https://github.com/YellowAfterlife/sfgml_verify
